// lib/schema.js - DDL Postgres. Dung INTEGER (tra ve number) + REAL cho he so.
// Cot chu thuong (Postgres tu ha thuong); tang db.js se doi key sang VIET HOA.
export const DROP_STATEMENTS = [
  'DROP TABLE IF EXISTS app_user CASCADE',
  'DROP TABLE IF EXISTS audit_log CASCADE',
  'DROP TABLE IF EXISTS khautru CASCADE',
  'DROP TABLE IF EXISTS thuong CASCADE',
  'DROP TABLE IF EXISTS bangluong CASCADE',
  'DROP TABLE IF EXISTS chamcong CASCADE',
  'DROP TABLE IF EXISTS nhanvien_phucap CASCADE',
  'DROP TABLE IF EXISTS phucap CASCADE',
  'DROP TABLE IF EXISTS nhanvien CASCADE',
  'DROP TABLE IF EXISTS chucvu CASCADE',
  'DROP TABLE IF EXISTS phongban CASCADE',
];

export const SCHEMA_STATEMENTS = [
  // matruongphong UNIQUE => 1 nhan vien chi lam truong phong toi da 1 phong (quan he 1-1 nhu tai lieu).
  // Postgres cho phep nhieu NULL nen phong chua co truong phong van hop le.
  `CREATE TABLE phongban (mapb integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     tenpb text, diadiem text, matruongphong integer UNIQUE)`,
  `CREATE TABLE chucvu (macv integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     tencv text, luongcoban integer, hesoluong real)`,
  // cmnd & email UNIQUE => khong cho trung nhan vien (khop tai lieu 2.3.3).
  // Postgres cho phep nhieu NULL nen NV chua nhap cmnd/email van hop le.
  `CREATE TABLE nhanvien (manv integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     hoten text, gioitinh text, ngaysinh text, cmnd text UNIQUE, dienthoai text, email text UNIQUE,
     diachi text, ngayvaolam text, mapb integer, macv integer, sotaikhoan text,
     trangthai text DEFAULT 'Dang lam')`,
  `CREATE TABLE phucap (mapc integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     tenpc text, sotien integer)`,
  `CREATE TABLE nhanvien_phucap (manv integer, mapc integer)`,
  `CREATE TABLE chamcong (macc integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     manv integer, thang integer, nam integer, songaycong real DEFAULT 0,
     songaynghi real DEFAULT 0, sogiotangca real DEFAULT 0)`,
  `CREATE TABLE bangluong (mabl integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     manv integer, thang integer, nam integer, luongcoban integer, tongphucap integer,
     tongthuong integer, luongtangca integer, bhxh integer, thuetncn integer,
     tongkhautru integer, luongthuclinh integer, ngaytao text)`,
  `CREATE TABLE thuong (mathuong integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     manv integer, thang integer, nam integer, lydo text, sotien integer)`,
  `CREATE TABLE khautru (makt integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     manv integer, thang integer, nam integer, lydo text, sotien integer)`,
  `CREATE TABLE audit_log (malog integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     tenbang text, hanhdong text, khoachinh text, nguoithuchien text, thoigian text, noidung text)`,
  `CREATE TABLE app_user (mauser integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     tendangnhap text, matkhau text, vaitro text, manv integer)`,
];
